[theme]
primaryColor = "#004AC6"
backgroundColor = "#FAF8FF"
secondaryBackgroundColor = "#F2F3FF"
textColor = "#131B2E"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
