[theme]
primaryColor = "#6366f1"
backgroundColor = "#060913"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
